[package]
name = "rust_2d_game"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.8.0-rc1"
mint = "0.5.8"
image = "0.24.2"
glam = "0.20.5"
serde_derive = "1.0"
serde = "1.0"
serde-xml-rs = "0.3.1"
